name: npm audit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm install
      - uses: oke-py/npm-audit-action@v1.7.1
        id: npm-audit-report
        with:
          json_flag: true
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
      - name: Write NPM Audit Report to File
        id: write-npm-report
        if: always()
        run: |
          echo $report > $HOME/npm-audit-report.json
        env:
          report: ${{steps.npm-audit-report.outputs.npm_audit}}
        shell: bash
      - uses: actions/setup-python@v2
        if: always()
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Convert report to SARIF format
        id: convert-sarif
        if: always()
        run: |
          python tools/convert-to-sarif.py $HOME/npm-audit-report.json > $HOME/npm-audit-report.sarif
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        env:
            TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sarif_file: $HOME/npm-audit-report.sarif